version: '3.9'

services:
    shore-app:
        container_name: shore-app
        image: shore-app
        stdin_open: true
        tty: true
        build: .
        environment:
            - FLASK_MAIL=enabled
            - DEBUG=False
        command: bash runner.sh
        ports:
            - "5002:5000"
        volumes:
            - .:/code
        depends_on:
            shore-app-db:
              condition: service_healthy
    shore-app-db:
        container_name: shore-app-db
        image: mysql
        ports:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=zxc90zxc
            - MYSQL_ROOT_HOST=%
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 20s
            timeout: 20s
            retries: 10
            start_period: 20s
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
    zaproxy:
      container_name: zaproxy
      image: owasp/zap2docker-weekly
      command: zap.sh -daemon -port 8090 -host 0.0.0.0
      ports:
      # ZAP is running on 8090, we want it to be accessible by our tools        
        - "8090:8090"
      depends_on:
        - shore-app
      volumes:
          - ./hook.py:/zap/hook.py

